const database = [
  {
    registration: 17,
    name: "Mari Fuentes",
    extension: 157,
    email: "mari_fuentes@ti.mobi",
    sector: "TI",
    birth: "1961-8-25",
  },
  {
    registration: 37,
    name: "Bolton Mack",
    extension: 637,
    email: "bolton_mack@operacional.ltda",
    sector: "Operacional",
    birth: "1960-7-27",
  },
  {
    registration: 11,
    name: "Marquita Klein",
    extension: 157,
    email: "marquita_klein@ti.om",
    sector: "TI",
    birth: "1952-4-4",
  },
  {
    registration: 29,
    name: "Berg Espinoza",
    extension: 155,
    email: "berg_espinoza@financeiro.windows",
    sector: "Financeiro",
    birth: "1956-2-20",
  },
  {
    registration: 2,
    name: "Osborne Black",
    extension: 581,
    email: "osborne_black@comercial.accountants",
    sector: "Comercial",
    birth: "1998-5-15",
  },
  {
    registration: 47,
    name: "Case Bowman",
    extension: 850,
    email: "case_bowman@financeiro.tokyo",
    sector: "Financeiro",
    birth: "1988-11-16",
  },
  {
    registration: 19,
    name: "Sexton Hardin",
    extension: 167,
    email: "sexton_hardin@operacional.latrobe",
    sector: "Operacional",
    birth: "1986-8-14",
  },
  {
    registration: 48,
    name: "Santiago Gardner",
    extension: 156,
    email: "santiago_gardner@operacional.run",
    sector: "Operacional",
    birth: "1989-5-18",
  },
  {
    registration: 38,
    name: "Meredith Hardy",
    extension: 339,
    email: "meredith_hardy@rh.how",
    sector: "RH",
    birth: "1963-7-12",
  },
  {
    registration: 21,
    name: "Ashley Brady",
    extension: 489,
    email: "ashley_brady@ti.mf",
    sector: "TI",
    birth: "1954-7-17",
  },
  {
    registration: 29,
    name: "Gillespie Webb",
    extension: 763,
    email: "gillespie_webb@operacional.claims",
    sector: "Operacional",
    birth: "1972-2-8",
  },
  {
    registration: 7,
    name: "Heath Mccall",
    extension: 980,
    email: "heath_mccall@financeiro.coupons",
    sector: "Financeiro",
    birth: "1998-12-6",
  },
  {
    registration: 25,
    name: "Delgado Sears",
    extension: 552,
    email: "delgado_sears@operacional.pharmacy",
    sector: "Operacional",
    birth: "1966-1-22",
  },
  {
    registration: 26,
    name: "Judith Waters",
    extension: 314,
    email: "judith_waters@administrativo.nl",
    sector: "Administrativo",
    birth: "1969-8-5",
  },
  {
    registration: 26,
    name: "Alissa Avery",
    extension: 196,
    email: "alissa_avery@operacional.work",
    sector: "Operacional",
    birth: "1970-9-20",
  },
  {
    registration: 19,
    name: "Schultz Guerra",
    extension: 254,
    email: "schultz_guerra@rh.vodka",
    sector: "RH",
    birth: "1999-5-20",
  },
  {
    registration: 43,
    name: "Annabelle Alvarez",
    extension: 940,
    email: "annabelle_alvarez@financeiro.xyz",
    sector: "Financeiro",
    birth: "1993-8-20",
  },
  {
    registration: 43,
    name: "Annette Holloway",
    extension: 452,
    email: "annette_holloway@operacional.neustar",
    sector: "Operacional",
    birth: "1964-7-22",
  },
  {
    registration: 7,
    name: "Sawyer Clarke",
    extension: 462,
    email: "sawyer_clarke@comercial.casino",
    sector: "Comercial",
    birth: "1987-11-21",
  },
  {
    registration: 45,
    name: "Garner Holden",
    extension: 424,
    email: "garner_holden@ti.navy",
    sector: "TI",
    birth: "1992-5-9",
  },
  {
    registration: 42,
    name: "Frank Hopper",
    extension: 466,
    email: "frank_hopper@ti.bank",
    sector: "TI",
    birth: "1996-3-22",
  },
  {
    registration: 34,
    name: "Kristina Sims",
    extension: 782,
    email: "kristina_sims@operacional.email",
    sector: "Operacional",
    birth: "2002-8-12",
  },
  {
    registration: 46,
    name: "Ortiz Mayo",
    extension: 507,
    email: "ortiz_mayo@financeiro.zm",
    sector: "Financeiro",
    birth: "2004-11-18",
  },
  {
    registration: 6,
    name: "Guy Griffin",
    extension: 477,
    email: "guy_griffin@financeiro.nf",
    sector: "Financeiro",
    birth: "1980-10-17",
  },
  {
    registration: 3,
    name: "Cornelia David",
    extension: 107,
    email: "cornelia_david@administrativo.tm",
    sector: "Administrativo",
    birth: "1964-8-21",
  },
  {
    registration: 17,
    name: "Gretchen Wise",
    extension: 691,
    email: "gretchen_wise@operacional.post",
    sector: "Operacional",
    birth: "1997-5-1",
  },
  {
    registration: 26,
    name: "Mitchell Leonard",
    extension: 589,
    email: "mitchell_leonard@administrativo.pl",
    sector: "Administrativo",
    birth: "1990-6-19",
  },
  {
    registration: 33,
    name: "Wood Cannon",
    extension: 108,
    email: "wood_cannon@rh.ninja",
    sector: "RH",
    birth: "1984-5-4",
  },
  {
    registration: 11,
    name: "Conway Hines",
    extension: 836,
    email: "conway_hines@financeiro.eurovision",
    sector: "Financeiro",
    birth: "1963-8-7",
  },
  {
    registration: 3,
    name: "Martina Bruce",
    extension: 787,
    email: "martina_bruce@comercial.dabur",
    sector: "Comercial",
    birth: "1982-9-5",
  },
];
module.exports = database;
/* 
// json generator
// https://next.json-generator.com/
// code to generate the json
JG.repeat(5, 10, {
    registration: JG.integer(2,50),
    name: `${JG.firstName()} ${JG.lastName()}`,
    extension: JG.integer(100,999),
    email() {
      return (
        _.snakeCase(this.profile.name) +
        '@' +
        this.profile.company +
        JG.domainZone()
      ).toLowerCase();
    },
    sector: JG.random('Administrativo', 'Financeiro', 'RH', 'Comercial', 'Operacional', 'TI'),
    birth: `${JG.integer(1950,2004)}-${JG.integer(1,12)}-${JG.integer(1,31)}`
  }); */
